/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Principal.Persona;
import Principal.Pokemon;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author arman
 */
public class SpecialAtk extends javax.swing.JFrame {
    Pokemon home;
    Pokemon rival;
    
    /**
     * Creates new form SpecialAtk
     */
    public SpecialAtk() {
        initComponents();
    }
    public SpecialAtk(Persona personaje, Pokemon home2, Pokemon rival2)
    {
        initComponents();
        home = home2;
        rival = rival2;
        lblPokemonHome.setText(home.nombre);
        
        normalHome.setEnabled(false);
        especialHome.setEnabled(false);
        usarHpHome.setEnabled(false);
        usarMpHome.setEnabled(false);
        TerminarHome.setEnabled(false);
        
        normalRival.setEnabled(false);
        especialRival.setEnabled(false);
        usarMpRival.setEnabled(false);
        usarHpRival.setEnabled(false);
        TerminarRival.setEnabled(false);
        
        ImageIcon imagen;
        Icon icono; 
        
        //Imagenes
        
        imagen = new ImageIcon(getClass().getResource("/Imagenes/" + home.nombre + ".png"));
        icono = new ImageIcon(imagen.getImage().getScaledInstance(lblBatallaPokemonHome.getWidth(), lblBatallaPokemonHome.getHeight(), Image.SCALE_DEFAULT));
        lblBatallaPokemonHome.setIcon(icono);
        lblBatallaHome.setText(home.nombre);
        
        imagen = new ImageIcon(getClass().getResource("/Imagenes/" + rival.nombre + ".png"));
        icono = new ImageIcon(imagen.getImage().getScaledInstance(lblBatallaPokemonRival.getWidth(), lblBatallaPokemonRival.getHeight(), Image.SCALE_DEFAULT));
        lblBatallaPokemonRival.setIcon(icono);
        lblBatallaRival.setText(rival.nombre);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpecialAtk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpecialAtk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpecialAtk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpecialAtk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpecialAtk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
